services:
  app:
    image: eth-crw-image
    container_name: eth-crw-container
    command:  /crw  --http-port 1080 --rps 10 --node-chan-size 10 --node-address https://mainnet.infura.io/v3/your-api-key
    ports:
      - "1080:1080"
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: .
      target: build
    volumes:
      - level_db:/app/ethereum_db
volumes:
  level_db:
