services:
  app:
    image: chain-crw-image
    container_name: chain-crw-container
    command:  /crw  --http-port 1080 --rps 10 --node-chan-size 10
      --eth-node-address your-api-key
        --bsc-node-address your-api-key
    ports:
      - "1080:1080"
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: .
      target: build
    volumes:
      - level_db:/app/dbStore
volumes:
  level_db:
