services:
  app:
    image: chain-crw-image
    container_name: chain-crw-container
    command:  /crw  start --rps 10 --node-chan-size 10
      --eth-node-address ${ETH_NODE_ADDRESS}
      --bsc-node-address ${BSC_NODE_ADDRESS}
    ports:
      - "1080:1080"
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: .
      target: build
    volumes:
      - level_db:/app/dbStore
volumes:
  level_db:
