openapi: 3.0.0
info:
    title: Chain Crawler API
    version: 1.0.0
    contact:
        email: amin.saradar@yahoo.com
    description: >-
      Explore the blockchain with our powerful Chain Crawler.
      This tool allows you to get detailed information about 
      Ethereum and Binance Smart Chain addresses, transactions, and blocks.
paths:
    "/status":
        get:
            operationId: GetStatus
            summary: Status
            description: |
                Returns an object containing the status response of the API.
                Meaning of status:
              
#                Address -  Ethereum address associated with the account.
#
#                TotalPaidFee - Total fees paid by the account.
#
#                LastHeight - The last known block associated with the account.
#
#                TxIndex - The last known transaction index related LastHeight.
#
#                FirstHeight - The initial block height where the account was first encountered.

            responses:
                "200":
                    $ref: '#/components/responses/StatusResponse'

    "/totalPaidFee/{address}":
        get:
            operationId: GetTotalPaidFee
            summary: Total Paid Fee
            description: Returns the total fees paid by the associated account
               with the provided address.
            parameters:
              - in: path
                name: address
                description: the account address
                required: true
                schema:
                  type: string
                example: '0xA1E4380A3B1f749673E270229993eE55F35663b4'
            responses:
              "200":
                $ref: '#/components/responses/TotalPaidFeeResponse'
    "/firstTransaction":
      get:
        operationId: GetFirstTransaction
        summary: First Transaction
        description: |
          Returns an object containing the first transaction of the chain
        responses:
          "200":
            $ref: '#/components/responses/FirstTransactionResponse'
components:
    responses:
        StatusResponse:
            description: Returns the status of crawler
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Status'
        TotalPaidFeeResponse:
          description: object  containing total paid fee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        FirstTransactionResponse:
            description: Object containing the first transaction of the chain
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Status'
    schemas:
        Status:
            type: object
            required:
                - address
                - totalPaidFee
                - lastHeight
                - txIndex
                - firstHeight
                - isContract
            properties:
              address:
                type: string
                description: the associated address with the account.
              totalPaidFee:
                type: integer
                format: uint64
                description: Total fees paid by the account, measured in uint64.
              lastHeight:
                type: integer
                format: int64
                description: The last known transaction index related LastHeight.
              txIndex:
                type: integer
                description: Transaction index related to the account.
              firstHeight:
                type: integer
                format: int64
                description: The initial block height where the account was first encountered.
              isContract:
                type: boolean
                default: false
                description: Is the address is a contract address or not.