name: Crw Test
on:
  push:
    branches:
      - master
      - test
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.21' ]
        os: [ ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      VM_DEBUG: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: go.mod
          cache: true
      - name: Tests
        run: make test-cover
